version: '3'
services:
  web:
    build: ./web
    ports:
      - "20017:5000"
    environment:
      - OAUTH_PROVIDER_URL=http://34.64.39.86:20018
    depends_on:
      - oauth-provider
  oauth-provider:
    build: ./oauth-provider
    ports:
      - "20018:6000"

